version: '3'
services:
  pihole:
    restart: unless-stopped
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    #ports:
    #  - "53:53/tcp"
    #  - "53:53/udp"
    #  - "67:67/udp"
    #  - "80:80/tcp"
    #  - "443:443/tcp"
    logging:
      options:
        tag: "{{.Name}}"
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: 'pihole'
      DNS1: ${PH_DNS1}
      DNS2: ${PH_DNS2}
      # Need ServerIP else lighttpd cannot start
      ServerIP: ${PH_SIP}
    volumes:
      - ${PH_ETC}:/etc/pihole
      - ${PH_DNS}:/etc/dnsmasq.d
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      # Required (DHCP needs NET_ADMIN)
      - NET_ADMIN
