version: '3'

services:
  elastiflow-elasticsearch-oss:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.3.0
    container_name: elastiflow-elasticsearch-oss
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    network_mode: host
    logging:
      options:
        tag: "{{.Name}}"
    volumes:
      - ${EF_DIR}:/usr/share/elasticsearch/data
    environment:
      # JVM Heap size
      #   - this should be at least 2GB for simple testing, receiving only a few flows per second.
      #   - for production environments upto 31GB is recommended.
      ES_JAVA_OPTS: '-Xms4g -Xmx4g'

      cluster.name: elastiflow

      bootstrap.memory_lock: 'true'

      network.host: 0.0.0.0
      http.port: 9200
      discovery.type: 'single-node'

      indices.query.bool.max_clause_count: 8192
      search.max_buckets: 100000

      action.destructive_requires_name: 'true'

  elastiflow-kibana-oss:
    image: docker.elastic.co/kibana/kibana-oss:7.3.0
    container_name: elastiflow-kibana-oss
    restart: always
    depends_on:
      - elastiflow-elasticsearch-oss
    network_mode: host
    logging:
      options:
        tag: "{{.Name}}"
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 5601

      ELASTICSEARCH_HOSTS: "http://127.0.0.1:9200"

      KIBANA_DEFAULTAPPID: "dashboard/653cf1e0-2fd2-11e7-99ed-49759aed30f5"

      LOGGING_QUIET: 'true'

  elastiflow-logstash-oss:
    image: robcowart/elastiflow-logstash-oss:3.5.1
    container_name: elastiflow-logstash-oss
    restart: always
    depends_on:
      - elastiflow-elasticsearch-oss
    network_mode: host
    logging:
      options:
        tag: "{{.Name}}"
    volumes:
      - ${EF_LS_CNF}:/etc/logstash/elastiflow/conf.d
      - ${EF_LS_HOS}:/tmp/hosts:ro
    environment:
      # JVM Heap size - this MUST be at least 3GB (4GB preferred)
      LS_JAVA_OPTS: '-Xms4g -Xmx4g'

      # ElastiFlow global configuration
      ELASTIFLOW_DEFAULT_APPID_SRCTYPE: "__UNKNOWN"

      # Name resolution option
      ELASTIFLOW_RESOLVE_IP2HOST: 'true'
      #ELASTIFLOW_NAMESERVER: "127.0.10.53"
      ELASTIFLOW_NAMESERVER: "127.0.0.53"

      #ELASTIFLOW_NETFLOW_IPV4_HOST: "127.0.0.1"
      #ELASTIFLOW_NETFLOW_IPV4_PORT: 2055
      ELASTIFLOW_NETFLOW_IPV6_PORT: 2055
      #ELASTIFLOW_SFLOW_IPV4_PORT: 6343
      #ELASTIFLOW_IPFIX_TCP_IPV4_PORT: 4739
      #ELASTIFLOW_IPFIX_TCP_IPV6_PORT: 4739
      ELASTIFLOW_IPFIX_UDP_IPV6_PORT: 4739
