version: '3'
services:
  gogs:
    restart: unless-stopped
    logging:
      options:
        tag: "{{.Name}}"
    image: gogs/gogs:${MY_GOGS_TAG}
    container_name: gogs
    ports:
      - "${MY_GOGS_SSH_PORT}:22"
      - "${MY_GOGS_WEB_PORT}:3000"
    volumes:
      - ${MY_GOGS_DIR}:/data
      - ${MY_SSL}:/data/ssl:ro